### ISSUE TITLE
(mod) add channel & guild filters

### ISSUE THREAD

**Issue by xsduan** [xsduan/conniebot#15]
blacklists, whitelists, etc

**Comment by xsduan** [comment]
not doing mod permissions

**Comment by xsduan** [comment]
possible reimplementation

**Comment by bbrk24** [comment]
I can understand why users may be blacklisted, but why channels? Couldn't they just remove the bot's permissions to view the channel?

**Comment by xsduan** [comment]
These are all just ideas I never got around to. You can close them if you want.
