### ISSUE TITLE
(x2i) extra typewriter alphabets

### ISSUE THREAD

**Issue by xsduan** [xsduan/conniebot#23]
From discord:

> Add extra typewriter alphabets probbly
> 
> - ARPABET https://en.wikipedia.org/wiki/ARPABET (arpa//, a// ?): no stress (although it’s already limited to English so like why not)
> - Kirshenbaum https://en.wikipedia.org/wiki/Kirshenbaum (kir//, k//?): probably not, or at least heavily restricted
> - analphabetic https://en.wikipedia.org/wiki/Phonetic_transcription#Analphabetic because why the fuck not
> - worldbet https://en.wikipedia.org/wiki/Worldbet if we can find any information on it

additional information:

> Arpabet in particular won’t be able to correctly translate stress because syllabification is something people write entire theses on and this is a silly bot that I wrote in 2 weeks.

-----

> Kirshenbaum might be an issue because of the way it allows abstract representations using feature bundles
> It would probably require some relatively complex parser or an overly massive conversion table to ensure that /{vls,alv,stp}{low,fnt,unr,vwl}{vcd,vel,stp}/ and /t&g/ get parsed the same(edited)
> It would also have to be context-aware to some extent given that . translates to either retroflex or rhotic (though *-SAMPA has this issue as well)

**Comment by bbrk24** [comment]
I could implement these if you're still interested. Probably not Analphabetic, but I could definitely manage the other ones.

Another one we could try to target is Praat's notation, which is unique in that all non-ASCII symbols have representations starting with `\`, except for ‖ which is `||`.

**Comment by bbrk24** [comment]
Praat's notation was added in v3.6.0. Another notation that has been requested is something akin to APIE but for Proto-Semitic. So far the informal standard we have is

> - `/p t k b d g/` -> \*p t k b d g
> - `/t. k. 7/` -> \*ṭ ḳ ʼ
> 
> - `/w y l m n h z/` -> \*w y l m n h z
> -  `/t- d- x/` -> \*ṯ ḏ ḫ
> - `/s1 s2 s3/` -> \*s₁ s₂ s₃
> - `/t-. h. g. s. l. c/` -> \*ṯ̣ ḥ ġ ṣ ṣ́ ʻ
> 
> - `/a i u/` -> \*a i u
> - `/a: i: u:/` -> \*ā ī ū

**Comment by xsduan** [comment]
If we're adding potentially a lot of different alphabets, it might be good to add a help: field so the help text would be something like:

```
{intro, x/help, x/invite, etc}

x/alphabets -- check which alphabets are available

{invite, etc}
```

and then when you do x/alphabets

```
X-SAMPA `x[]` -- <link to x-sampa wiki>
Z-SAMPA `z[]` -- <link to z-sampa wiki>
...
```

which is all dynamically built.

Another thing to consider is using the slash commands to make it more visible.

**Comment by bbrk24** [comment]
I'd rather not use slash commands, in part for practical reasons -- all the servers where beberkonnie is already present invited it with `scope=bot`, but slash commands require `scope=bot%20applications.commands`.

I am in favor of the change to the help menu you suggested, though.

**Comment by xsduan** [comment]
Fair enough, though we could always gracefully degrade for permissions. Unsure if there's an "upgrade" action for permissions…they could always reinvite the bot.

**Comment by bbrk24** [comment]
I'm going to close this issue since more alphabets have been added. With the introduction of @mszegedy's ASCIIPA 2 (currently only on the dev branch), there aren't any more requested alphabets that could feasibly be implemented.
