### ISSUE TITLE
Z-SAMPA reference page link out of date

### ISSUE THREAD

**Issue by mszegedy** [xsduan/conniebot#28]
The [current link](http://kneequickie.com/kq/Z-SAMPA) gives a 404. But [the most recent Wayback Machine copy](https://web.archive.org/web/20191116002807/http://kneequickie.com/kq/Z-SAMPA) still works. So the link in the help message should be updated. Probably to the latter link, unless anyone has a better idea.

**Comment by xsduan** [comment]
I've changed it so that it's completely up to the user to configure the help text, but I have updated the link on my discord bot. Thank you for bringing this up!
