### ISSUE TITLE
z-sampa duplicated tiebars

### ISSUE THREAD

**Issue by berrymot** [xsduan/conniebot#48]
![image](https://user-images.githubusercontent.com/50974538/224822660-4b68818a-943b-46cb-84e4-7dd60b40e06e.png)

there should be only one tiebar, on top of the `t`

also partial voicing and affricates don't play nicely: if i want a voiced /ts/, `z/t_vs_v)/` gives `/t̬s̬₎/`

**Comment by bbrk24** [comment]
The bot handles tie bars differently from the Z-SAMPA standard:

- Some affricates get a tie bar automatically, like `z/ts/`. To prevent this, you have to say `z/t-s/`.
- When you need to explicitly add a tie bar, put it *between* the letters, not after them: `z/c)C/`.

I'm not sure there's anything I can do about the partial voicing diacritic issue.

**Comment by berrymot** [comment]
ah

**Comment by bbrk24** [comment]
Actually, there is a workaround for the partial voicing diacritic: `z/t_v-)s_v/`.
